[build]
  base = "frontend"
  publish = "build"
  command = "npm install --legacy-peer-deps && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  DISABLE_ESLINT_PLUGIN = "true"
