[build]
  base = "frontend"
  publish = "build"
  command = "npm install --force && CI=false npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"
